services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - "8080:8000"

  pg:
    image: postgres
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: mindcore
      POSTGRES_PASSWORD: mindcore
    ports:
      - "5433:5432"

