services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - "8080:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0

  pg:
    image: postgres
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: mindcore
      POSTGRES_PASSWORD: mindcore
    ports:
      - "5433:5432"

  redis:
    image: redis:7.0-alpine
    ports:
      - '6379:6378'
