services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - "8080:8000"

  pg:
    image: postgres
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: mindcore
      POSTGRES_PASSWORD: mindcore
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"