"""add balance

Revision ID: 02a826ba149e
Revises: 3a583ddb7f77
Create Date: 2025-06-09 01:42:19.167175

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "02a826ba149e"
down_revision: Union[str, None] = "3a583ddb7f77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bank_accounts",
        sa.Column(
            "balance", sa.DECIMAL(precision=10, scale=2), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bank_accounts", "balance")
    # ### end Alembic commands ###
